
AM_CPPFLAGS=-x c++ $(DEBUG) -I$(top_srcdir)/cxcore/cxcore/include/ -I$(top_srcdir)/c_pgmtk/include/ -I$(top_srcdir)/c_pgmtk/src/include/ -Wno-vla
PNLD=$(top_srcdir)/c_pgmtk
PNLBUILDD=$(top_builddir)/c_pgmtk
PNL_LIBS=$(PNLBUILDD)/src/libpnl.la $(top_builddir)/cxcore/cxcore/src/libcxcore.la -ldl
PNL_INCL=-I$(top_srcdir)/cxcore/cxcore/include -I$(PNLD)/include -I$(PNLD)/src/include/cart -I$(PNLD)/src/include

