#!/usr/bin/env python
import os
import sipconfig

# The name of the SIP build file generated by SIP and used by the build
# system.
build_file = "pnl.sbf"

# Get the SIP configuration information.
config = sipconfig.Configuration()

# Run SIP to generate the code.
os.system(" ".join([config.sip_bin, "-c", ".", "-b", build_file, "pnl.sip"]))

# Create the Makefile.
makefile = sipconfig.SIPModuleMakefile(config, build_file)

# Add the library we are wrapping.  The name doesn't include any platform
# specific prefixes or extensions (e.g. the "lib" prefix on UNIX, or the
# ".dll" extension on Windows).
makefile.extra_libs = ["pnl"]
makefile.extra_lib_dirs = ["../../prefix/lib/"]
#makefile.extra_include_dirs = ["../prefix/include/"]
makefile.extra_include_dirs = ["../../prefix/include/","../../prefix/include/opencx/"]
#makefile.extra_include_dirs = ["../c_pgmtk/include/", "../c_pgmtk/include/" "../c_pgmtk/src/include/", "../cxcore/cxcore/include/", " ../high/include/", "../c_pgmtk/src/include/"]


# Generate the Makefile itself.
makefile.generate()
